language: node_js
node_js:
  - 6
services: mongodb
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
  - npm install
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - SENDGRID_KEY=sendgridKey
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret