language: node_js
node_js:
  - 6
notifications:
  email:
    recipients:
      - hmtilano@tie-in.co
    on_success: never
    on_failure: always
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
services: mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_script:
  - npm install
script:
  - npm test -- -i --coverage
after_success:
  - npm run corp-release -- --verbose
env:
  global:
  - CXX=g++-4.8
  - SENDGRID_KEY=sendgridKey
  - MASTER_KEY=masterKey
  - JWT_SECRET=jwtSecret